const dom = {
  nfcDialog: document.getElementById("nfcDialog"),
  nfcWarning: document.getElementById("nfcWarning"),
  fetchingPlayer: document.getElementById("fetchingPlayer"),
  leaderboardBody: document.getElementById("topScoresBody"),
  runningRightNowBody: document.getElementById("runningRightNowBody"),
  welcomeBack: {
    container: document.getElementById("welcomeBackRegistered"),
    name: document.getElementById("welcomeBackRegisteredName"),
    pfp: document.getElementById("welcomeBackRegisteredPfp"),
    program: document.getElementById("welcomeBackRegisteredProgram"),
  },
  registration: {
    container: document.getElementById("registration"),
    basicInfoPage: {
      container: document.getElementById("registrationBasicInfoPage"),
      form: document.getElementById("registerForm"),
      username: document.getElementById("registerUsername"),
      program: document.getElementById("registerProgram"),
      content: document.getElementById("registerTermsContent"),
      cancel: document.getElementById("registerCancel"),
    },
    pfpPage: {
      container: document.getElementById("registrationPfpPage"),
      video: document.getElementById("registration-pfp-video"),
      canvas: document.getElementById("registration-pfp-canvas"),
      photo: document.getElementById("registration-pfp-photo"),
      countdown: document.getElementById("registration-pfp-countdown"),
      captureButton: document.getElementById("registration-pfp-capture-button"),
      clearButton: document.getElementById("registration-pfp-clear-button"),
      useButton: document.getElementById("registration-pfp-use"),
      skipButton: document.getElementById("registration-pfp-skip"),
    },
    finishPage: {
      container: document.getElementById("registration-finish-page"),
      name: document.getElementById("registration-finish-name"),
      pfp: document.getElementById("registration-finish-pfp"),
      program: document.getElementById("registration-finish-program"),
    },
  },
};
