const dom = {
  nfcDialog: document.getElementById("nfcDialog"),
  nfcWarning: document.getElementById("nfcWarning"),
  fetchingPlayer: document.getElementById("fetchingPlayer"),
  topScoresCount: document.getElementById("topScoresCount"),
  leaderboardBody: document.getElementById("topScoresBody"),
  runningRightNowCount: document.getElementById("runningRightNowCount"),
  runningRightNowBody: document.getElementById("runningRightNowBody"),
  welcomeBack: {
    container: document.getElementById("welcomeBackRegistered"),
    name: document.getElementById("welcomeBackRegisteredName"),
    pfp: document.getElementById("welcomeBackRegisteredPfp"),
    otherStation: document.getElementById("welcome-back-other-station"),
    runInfo: {
      container: document.getElementById("welcomeBackRunInfo"),
      newRunContainer: document.getElementById("welcomeBackNewRun"),
      prevRunContainer: document.getElementById("welcomeBackPrevRun"),
      stations: document.getElementById("welcomeBackRunStations"),
      prevStations: document.getElementById("welcomeBackPrevStations"),
      time: document.getElementById("welcomeBackRunTime"),
      prevTime: document.getElementById("welcomeBackPrevTime"),
      positionNote: document.getElementById("welcomeBackRunPositionNote"),
    },
  },
  registration: {
    container: document.getElementById("registration"),
    qrCodeContainer: document.getElementById("registrationQrCodeContainer"),
  },
  runSummary: {
    container: document.getElementById("runSummaryPage"),
    title: document.getElementById("runSummaryTitle"),
    containerInner: document.getElementById("runSummary"),
    newRunContainer: document.getElementById("runSummaryNewRun"),
    prevRunContainer: document.getElementById("runSummaryPrevRun"),
    prevLabel: document.getElementById("runSummaryPrevLabel"),
    stations: document.getElementById("runSummaryStations"),
    prevStations: document.getElementById("runSummaryPrevStations"),
    time: document.getElementById("runSummaryTime"),
    prevTime: document.getElementById("runSummaryPrevTime"),
    leaderboardBody: document.getElementById("runSummaryLeaderboardBody"),
  },
  dialogTimer: {
    container: document.getElementById("dialogTimer"),
    bar: document.getElementById("dialogTimerBar"),
    label: document.getElementById("dialogTimerLabel"),
  },
};
